"""The Safari page script is generated; fail if someone edited the source without rebuilding."""
import pathlib

EXT = pathlib.Path(__file__).resolve().parent.parent / "ios" / "RetAIn" / "ActionExt"


def test_page_js_bundle_is_current():
    expected = ("// GENERATED by make-page-js.sh from vendor/Readability.js + RetAInPage.src.js — do not edit.\n"
                + (EXT / "vendor" / "Readability.js").read_text() + "\n" + (EXT / "RetAInPage.src.js").read_text())
    assert (EXT / "RetAInPage.js").read_text() == expected, "run ios/RetAIn/ActionExt/make-page-js.sh"
