#!/bin/sh
# Safari runs exactly one preprocessing file, so bundle the vendored library ahead of our code.
# Run after editing RetAInPage.src.js; tests/test_page_js.py fails if RetAInPage.js is stale.
cd "$(dirname "$0")"
{ echo "// GENERATED by make-page-js.sh from vendor/Readability.js + RetAInPage.src.js — do not edit."
  cat vendor/Readability.js; echo; cat RetAInPage.src.js; } > RetAInPage.js
